### ISSUE TITLE
Error importing the addon

### ISSUE THREAD

**Issue by BenBKirk** [stevetasticsteve/Anki_bulk_importer#5]
Hi Steve, 
I wonder if you still remember me from MTC?
We are in NCLA at the moment and this addon would be really useful for some of the new guys here.

Unfortunately, we are getting an error on windows. I have tried an older version of anki but the problem doesn't go away.

Here is a picture of the error:
![2021-01-22 09_01_09-Anki](https://user-images.githubusercontent.com/77818857/105438485-a13dda80-5c95-11eb-90be-ca06209ae0a5.jpg)

All the best,
Ben Kirk

Edit:

I tried replacing that part of the code (addonDir) with a raw string of the PATH to the directory it is struggling to find and this enable the addon to load without an error however if I click of the addon under the tools menu nothing happens.

Edit2:
The first time, I tried installing by copying and pasting the code straight into Anki (that resulted in the error above.)  but now I tried the other method of installing it, by unzipping and manually pasting it into the addons folder under a folder named "bulk_importer" and it works. I wonder if the problem is how the main directory is named when installing via Anki. I think it gets the name of the code (1312111882).

**Comment by stevetasticsteve** [comment]
Hi Ben
Yes, the error is because I've always named the folder 'bulk_importer' and that's hard coded in as the variable addonDir in __init__.py

I added it into anki's add-on directory as an after thought and didn't test it properly. The add-on variable needs to recognise a folder named 1312111882, as that's what the anki add-on directory calls it. 

My guess is fix #1 you tried didn't get it because addonDir is used more than once and perhaps your tweak enabled it to initialise, but something else broke afterwards and the add-on crashed trying to present it's dialog window. 

I'll add a try/except so both are valid options and reupload to anki.com today

**Comment by BenBKirk** [comment]
Nice, thank you for sharing for work for other to benefit from!

**Comment by stevetasticsteve** [comment]
No problem
The issue has been fixed and you can install the addon using the code 1312111882. I've tested it in windows with Anki 2.1.38 (the latest version).

addonDir was defined in two places, thus you needed to change both of them. Paths.py now takes care of providing a path variable for it to use that defaults to looking for a folder with the correct number and looks for a folder named bulk_importer as a 2nd choice.
